import { ITrack, Artwork, RemixOf, User, Stream, Access, FieldVisibility } from "@/interfaces/Track";

export const emptyTrack: ITrack = {
  track_id: 0,
  description: "",
  genre: "",
  id: "",
  track_cid: "",
  preview_cid: null,
  orig_file_cid: "",
  orig_filename: "",
  is_original_available: false,
  mood: "",
  release_date: "",
  repost_count: 0,
  favorite_count: 0,
  comment_count: 0,
  tags: "",
  title: "",
  slug: "",
  duration: 0,
  is_downloadable: false,
  play_count: 0,
  ddex_app: null,
  pinned_comment_id: null,
  playlists_containing_track: [],
  playlists_previously_containing_track: {},
  album_backlink: null,
  blocknumber: 0,
  create_date: null,
  created_at: "",
  cover_art_sizes: "",
  credits_splits: null,
  isrc: null,
  license: "",
  iswc: null,
  field_visibility: {} as FieldVisibility,
  has_current_user_reposted: false,
  has_current_user_saved: false,
  is_scheduled_release: false,
  is_unlisted: false,
  stem_of: null,
  track_segments: [],
  updated_at: "",
  is_delete: false,
  cover_art: null,
  is_available: false,
  ai_attribution_user_id: null,
  allowed_api_keys: null,
  audio_upload_id: null,
  preview_start_seconds: null,
  bpm: 0,
  is_custom_bpm: false,
  musical_key: "",
  is_custom_musical_key: false,
  audio_analysis_error_count: 0,
  comments_disabled: false,
  ddex_release_ids: null,
  artists: null,
  resource_contributors: null,
  indirect_resource_contributors: null,
  rights_controller: null,
  copyright_line: null,
  producer_copyright_line: null,
  parental_warning_type: null,
  is_stream_gated: false,
  is_download_gated: false,
  cover_original_song_title: null,
  cover_original_artist: null,
  is_owned_by_user: false,
  access_authorities: null,
  permalink: "",
  is_streamable: false,
  artwork: {} as Artwork,
  stream: {} as Stream,
  download: null,
  preview: null,
  user_id: "",
  user: {} as User,
  access: {} as Access,
  followee_reposts: [],
  followee_favorites: [],
  remix_of: {} as RemixOf,
  stream_conditions: null,
  download_conditions: null,
};
