export interface IList {
  artwork: Artwork
  description: string
  permalink: string
  id: string
  is_album: boolean
  is_image_autogenerated: boolean
  playlist_name: string
  playlist_contents: PlaylistContent[]
  repost_count: number
  favorite_count: number
  total_play_count: number
  user: User
  ddex_app: string
  access: Access
  upc: string
  track_count: number
}

export interface Artwork {
  "150x150": string
  "480x480": string
  "1000x1000": string
}

export interface PlaylistContent {
  metadata_timestamp: number
  timestamp: number
  track_id: string
}

export interface User {
  album_count: number
  artist_pick_track_id?: string
  bio: string
  cover_photo: CoverPhoto
  followee_count: number
  follower_count: number
  handle: string
  id: string
  is_verified: boolean
  twitter_handle?: string
  instagram_handle?: string
  tiktok_handle?: string
  verified_with_twitter: boolean
  verified_with_instagram: boolean
  verified_with_tiktok: boolean
  website?: string
  donation?: string
  location: string
  name: string
  playlist_count: number
  profile_picture: ProfilePicture
  repost_count: number
  track_count: number
  is_deactivated: boolean
  is_available: boolean
  erc_wallet: string
  spl_wallet: string
  spl_usdc_payout_wallet: null
  supporter_count: number
  supporting_count: number
  total_audio_balance: number
  wallet: string
}

export interface CoverPhoto {
  "640x": string
  "2000x": string
}

export interface ProfilePicture {
  "150x150": string
  "480x480": string
  "1000x1000": string
}

export interface Access {
  stream: boolean
  download: boolean
}
